/**
 * Regenerates `src/ts/sound/rustyvibes/catalog.ts` - the browser soundpack catalog.
 *
 * Inputs:
 *   - `scripts/data/rustyvibes-catalog.json` (copy of rustyvibes-v2
 *     `assets/soundpacks/catalog.json`, the upstream source of truth)
 *   - `static/sounds/rustyvibes/<id>.rvw` (the browser soundpacks)
 *
 * Run with: pnpm generate-rustyvibes-catalog
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { decodeRvw } from "../src/ts/sound/rustyvibes/rvw";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const frontendDir = path.resolve(scriptDir, "..");
const catalogJsonPath = path.join(scriptDir, "data", "rustyvibes-catalog.json");
const packsDir = path.join(frontendDir, "static", "sounds", "rustyvibes");
const outPath = path.join(
  frontendDir,
  "src",
  "ts",
  "sound",
  "rustyvibes",
  "catalog.ts",
);

/** Pack used when a config points at a missing/invalid id (and the web default). */
const WEB_DEFAULT_PACK = "holy-panda";

const CATEGORIES = ["linear", "tactile", "clicky"] as const;

type UpstreamPack = {
  id: string;
  name: string;
  variant?: string;
  category: string;
  color: string;
  credit: string;
};

type UpstreamCatalog = {
  default: string;
  packs: UpstreamPack[];
};

function readPackFile(id: string): { bytes: number; hasRelease: boolean } {
  const file = path.join(packsDir, `${id}.rvw`);
  const buf = fs.readFileSync(file);
  const arrayBuffer = buf.buffer.slice(
    buf.byteOffset,
    buf.byteOffset + buf.byteLength,
  );
  const { header } = decodeRvw(arrayBuffer);
  if (header.id !== id) {
    throw new Error(
      `${id}.rvw contains soundpack id "${header.id}" - asset and catalog disagree`,
    );
  }
  return {
    bytes: buf.byteLength,
    hasRelease: Object.keys(header.release).length > 0,
  };
}

function main(): void {
  const catalog = JSON.parse(
    fs.readFileSync(catalogJsonPath, "utf8"),
  ) as UpstreamCatalog;

  const generated = catalog.packs.map((pack) => {
    if (!(CATEGORIES as readonly string[]).includes(pack.category)) {
      throw new Error(
        `pack ${pack.id} has unknown category "${pack.category}"`,
      );
    }
    const { bytes, hasRelease } = readPackFile(pack.id);
    return {
      id: pack.id,
      name: pack.name,
      ...(pack.variant !== undefined ? { variant: pack.variant } : {}),
      category: pack.category,
      color: pack.color,
      credit: pack.credit,
      url: `../sounds/rustyvibes/${pack.id}.rvw`,
      bytes,
      hasRelease,
    };
  });

  const ids = generated.map((pack) => pack.id);
  if (new Set(ids).size !== ids.length) {
    throw new Error("duplicate pack ids in the catalog");
  }
  if (!ids.includes(WEB_DEFAULT_PACK)) {
    throw new Error(`default pack "${WEB_DEFAULT_PACK}" is missing`);
  }

  const entries = generated
    .map((pack) => `  ${JSON.stringify(pack)},`)
    .join("\n");

  const output = `// AUTO-GENERATED by scripts/generate-rustyvibes-catalog.ts - do not edit.
// Source of truth: rustyvibes-v2 assets/soundpacks/catalog.json (MIT).
// Soundpack recordings: Mechvibes by Hai Nguyen and kbsim by Thomas Lai (MIT).

export type SoundpackCategory = (typeof CATEGORIES)[number];

export const CATEGORIES = ["linear", "tactile", "clicky"] as const;

export type PackInfo = {
  id: string;
  name: string;
  variant?: string;
  category: SoundpackCategory;
  color: string;
  credit: string;
  url: string;
  bytes: number;
  hasRelease: boolean;
};

/** Every browser soundpack, in upstream catalog order. */
export const PACKS: readonly PackInfo[] = [
${entries}
];

/** Soundpack used when the configured id is unknown or invalid. */
export const DEFAULT_PACK = ${JSON.stringify(WEB_DEFAULT_PACK)};

export function findPack(id: string): PackInfo | undefined {
  return PACKS.find((pack) => pack.id === id);
}

/** "Cherry MX Black" + "ABS" -> "Cherry MX Black ABS". */
export function packLabel(pack: PackInfo | string): string {
  const info = typeof pack === "string" ? findPack(pack) : pack;
  if (info === undefined) return typeof pack === "string" ? pack : "";
  return info.variant !== undefined
    ? \`\${info.name} \${info.variant}\`
    : info.name;
}
`;

  fs.writeFileSync(outPath, output);
  console.log(`wrote ${path.relative(frontendDir, outPath)}`);
}

main();
