// AUTO-GENERATED by scripts/generate-rustyvibes-catalog.ts - do not edit.
// Source of truth: scripts/data/rustyvibes-catalog.json (upstream rustyvibes-v2
// catalog + the short descriptions shown on the switch selector).
// Soundpack recordings: Mechvibes by Hai Nguyen and kbsim by Thomas Lai (MIT).

export type SoundpackCategory = (typeof CATEGORIES)[number];

export const CATEGORIES = ["linear", "tactile", "clicky"] as const;

export type PackInfo = {
  id: string;
  name: string;
  variant?: string;
  category: SoundpackCategory;
  description: string;
  color: string;
  credit: string;
  url: string;
  bytes: number;
  hasRelease: boolean;
};

/** Every browser soundpack, in upstream catalog order. */
export const PACKS: readonly PackInfo[] = [
  {
    id: "cherry-mx-black-abs",
    name: "Cherry MX Black",
    variant: "ABS",
    category: "linear",
    description: "Heavy, smooth, low",
    color: "#2C2C30",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-black-abs.rvw",
    bytes: 444628,
    hasRelease: true,
  },
  {
    id: "cherry-mx-black-pbt",
    name: "Cherry MX Black",
    variant: "PBT",
    category: "linear",
    description: "Heavy, smooth, deeper",
    color: "#2C2C30",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-black-pbt.rvw",
    bytes: 333494,
    hasRelease: false,
  },
  {
    id: "cherry-mx-red-abs",
    name: "Cherry MX Red",
    variant: "ABS",
    category: "linear",
    description: "Light and quick",
    color: "#D7263D",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-red-abs.rvw",
    bytes: 392186,
    hasRelease: false,
  },
  {
    id: "cherry-mx-red-pbt",
    name: "Cherry MX Red",
    variant: "PBT",
    category: "linear",
    description: "Light, quick, rounder",
    color: "#D7263D",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-red-pbt.rvw",
    bytes: 377610,
    hasRelease: false,
  },
  {
    id: "gateron-black-ink",
    name: "Gateron Black Ink",
    category: "linear",
    description: "Deep and silky",
    color: "#3A3F4A",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/gateron-black-ink.rvw",
    bytes: 73436,
    hasRelease: true,
  },
  {
    id: "gateron-red-ink",
    name: "Gateron Red Ink",
    category: "linear",
    description: "Bright and silky",
    color: "#B3203B",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/gateron-red-ink.rvw",
    bytes: 86644,
    hasRelease: true,
  },
  {
    id: "novelkeys-cream",
    name: "NovelKeys Cream",
    category: "linear",
    description: "Warm and marbly",
    color: "#EBD9B4",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/novelkeys-cream.rvw",
    bytes: 78228,
    hasRelease: true,
  },
  {
    id: "alpaca",
    name: "Alpaca",
    category: "linear",
    description: "Soft and poppy",
    color: "#F2A7C3",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/alpaca.rvw",
    bytes: 84354,
    hasRelease: true,
  },
  {
    id: "turquoise-tealios",
    name: "Turquoise Tealios",
    category: "linear",
    description: "Clean and even",
    color: "#2EC4B6",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/turquoise-tealios.rvw",
    bytes: 74708,
    hasRelease: true,
  },
  {
    id: "cherry-mx-brown-abs",
    name: "Cherry MX Brown",
    variant: "ABS",
    category: "tactile",
    description: "A gentle bump",
    color: "#8B5A2B",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-brown-abs.rvw",
    bytes: 342330,
    hasRelease: false,
  },
  {
    id: "cherry-mx-brown-pbt",
    name: "Cherry MX Brown",
    variant: "PBT",
    category: "tactile",
    description: "A gentle bump, fuller",
    color: "#8B5A2B",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-brown-pbt.rvw",
    bytes: 392216,
    hasRelease: false,
  },
  {
    id: "holy-panda",
    name: "Holy Panda",
    category: "tactile",
    description: "Rounded thock",
    color: "#E9A23B",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/holy-panda.rvw",
    bytes: 78552,
    hasRelease: true,
  },
  {
    id: "topre",
    name: "Topre",
    category: "tactile",
    description: "Cushioned thock",
    color: "#8E8E93",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/topre.rvw",
    bytes: 101840,
    hasRelease: true,
  },
  {
    id: "topre-purple-hybrid-pbt",
    name: "Topre Purple Hybrid",
    variant: "PBT",
    category: "tactile",
    description: "Deep, damped thock",
    color: "#7E57C2",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/topre-purple-hybrid-pbt.rvw",
    bytes: 384466,
    hasRelease: false,
  },
  {
    id: "everglide-crystal-purple",
    name: "Everglide Crystal Purple",
    category: "tactile",
    description: "Bright and snappy",
    color: "#A77BF3",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/everglide-crystal-purple.rvw",
    bytes: 293872,
    hasRelease: false,
  },
  {
    id: "everglide-oreo",
    name: "Everglide Oreo",
    category: "tactile",
    description: "Punchy and dense",
    color: "#3B3B3B",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/everglide-oreo.rvw",
    bytes: 273480,
    hasRelease: false,
  },
  {
    id: "cherry-mx-blue-abs",
    name: "Cherry MX Blue",
    variant: "ABS",
    category: "clicky",
    description: "Crisp, loud click",
    color: "#1F6FEB",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-blue-abs.rvw",
    bytes: 406698,
    hasRelease: false,
  },
  {
    id: "cherry-mx-blue-pbt",
    name: "Cherry MX Blue",
    variant: "PBT",
    category: "clicky",
    description: "Crisp click, fuller",
    color: "#1F6FEB",
    credit: "Mechvibes by Hai Nguyen · MIT License",
    url: "../sounds/rustyvibes/cherry-mx-blue-pbt.rvw",
    bytes: 397994,
    hasRelease: false,
  },
  {
    id: "kailh-box-navy",
    name: "Kailh Box Navy",
    category: "clicky",
    description: "Heavy, sharp click",
    color: "#1B2F5E",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/kailh-box-navy.rvw",
    bytes: 96638,
    hasRelease: true,
  },
  {
    id: "skcm-blue-alps",
    name: "SKCM Blue Alps",
    category: "clicky",
    description: "Crisp, hollow click",
    color: "#5AA9E6",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/skcm-blue-alps.rvw",
    bytes: 102574,
    hasRelease: true,
  },
  {
    id: "buckling-spring",
    name: "Buckling Spring",
    category: "clicky",
    description: "Loud, springy clack",
    color: "#CFC6B4",
    credit: "kbsim by Thomas Lai · MIT License",
    url: "../sounds/rustyvibes/buckling-spring.rvw",
    bytes: 115752,
    hasRelease: true,
  },
];

/** Soundpack used when the configured id is unknown or invalid. */
export const DEFAULT_PACK = "holy-panda";

export function findPack(id: string): PackInfo | undefined {
  return PACKS.find((pack) => pack.id === id);
}

/** "Cherry MX Black" + "ABS" -> "Cherry MX Black ABS". */
export function packLabel(pack: PackInfo | string): string {
  const info = typeof pack === "string" ? findPack(pack) : pack;
  if (info === undefined) return typeof pack === "string" ? pack : "";
  return info.variant !== undefined
    ? `${info.name} ${info.variant}`
    : info.name;
}
